# Generated by Django 5.1.1 on 2024-12-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='duration',
            field=models.CharField(max_length=10),
        ),
    ]
